name: CD

on:
  push:
    branches: [master]
  pull_request:
  release:
    types: [published]

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      MACOSX_DEPLOYMENT_TARGET: "11.0"
      CIBW_BUILD_VERBOSITY: "1"
      CIBW_ARCHS_MACOS: "x86_64 arm64"
      CIBW_BEFORE_BUILD_MACOS: >
        brew install libomp &&
        brew install llvm
      CIBW_ENVIRONMENT_MACOS: >
        MACOSX_DEPLOYMENT_TARGET=11.0
        PATH="/usr/local/opt/llvm/bin:$PATH"
        CC="/usr/local/opt/llvm/bin/clang"
        CXX="/usr/local/opt/llvm/bin/clang++"
        CFLAGS="-I/usr/local/opt/libomp/include"
        CXXFLAGS="-I/usr/local/opt/libomp/include"
        LDFLAGS="-L/usr/local/opt/libomp/lib -Wl,-rpath,/usr/local/opt/libomp/lib"
      CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
        DYLD_LIBRARY_PATH=/usr/local/opt/libomp/lib:/usr/local/lib
        delocate-listdeps {wheel} &&
        delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: get repo
        uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: |
          pip install --upgrade setuptools packaging
          pip install numpy cython
          python setup.py sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  twine_check:
    name: Check if dists can be published
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name != 'release'

    steps:
      - name: Download wheels and sdist
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Check with twine
        run: |
          pip install twine
          pip install -U packaging
          twine check dist/* --strict

  publish:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - name: Download wheels and sdist
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        run: |
          pip install twine
          pip install -U packaging
          twine upload dist/* -u __token__ -p ${{ secrets.pypi_token }}